version: '3.8'

services:
  web:
    build: ./src
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - ucar:/var/lib/src
      - /src/app:/src/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://namnn:namnn@db:5432/namnn
    depends_on:
      - db
    env_file:
      - ./src/.env
  db:
    image: postgres:15-alpine
    volumes:
      - ucar:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER="namnn"
      - POSTGRES_PASSWORD="namnn"
      - POSTGRES_DB="UCar"

volumes:
  ucar: